### ISSUE TITLE
测试环境无法播放问题

### ISSUE THREAD

**Issue by zsinba** [NodeMedia/NodeMediaServer#3]
NMSv3.4.0及之后版本可用, 先使用WebSocket与NMS之间交换信令, 再创建客户端到服务端之间的webrtc连接.
客户端向服务端推送H264+Opus编码的流,服务端再封装为rtmp/kmp/http-flv/hls等协议提供客户端播放.
支持软硬件编码,1080超高清无压力 Opus音频编码可在服务端实时转码为AAC
支持最新版Chrome,Edge,firefox及使用chromium内核的浏览器,无需安装插件,不限操作系统.

测试地址：https://live.nodemedia.cn/rtcdemo.html

这个测试地址，出来的flv地址播放不出来呀。
 我是使用你们官方的H5版本的Flv播放器尝试的，播放不出来。请问这个是还没发布，还是？？

**Comment by illuspas** [comment]
什么版本浏览器
打开控制台，查看是否有错误输出

**Comment by zsinba** [comment]
demo的console
cp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:123 H264/90000
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 transport-cc
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=123
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=ssrc-group:FID 4112186636 353621231
a=ssrc:4112186636 cname:bXNIzuMgVnXvYuQF
a=ssrc:4112186636 msid:8lieS7OnVN3QFGiCQTtBlXeQRjVkn4y6eLZo feb58f87-daf6-4b82-bbc4-89ce0bdc9307
a=ssrc:4112186636 mslabel:8lieS7OnVN3QFGiCQTtBlXeQRjVkn4y6eLZo
a=ssrc:4112186636 label:feb58f87-daf6-4b82-bbc4-89ce0bdc9307
a=ssrc:353621231 cname:bXNIzuMgVnXvYuQF
a=ssrc:353621231 msid:8lieS7OnVN3QFGiCQTtBlXeQRjVkn4y6eLZo feb58f87-daf6-4b82-bbc4-89ce0bdc9307
a=ssrc:353621231 mslabel:8lieS7OnVN3QFGiCQTtBlXeQRjVkn4y6eLZo
a=ssrc:353621231 label:feb58f87-daf6-4b82-bbc4-89ce0bdc9307

nmrtc.js:56 onopen
nmrtc.js:61 onmessage e= {method: "onpublish", error: "", audio: {…}, video: {…}, description: {…}}
nmrtc.js:43 oniceconnectionstatechange: checking
nmrtc.js:70 onclose



播放器使用的:
http://www.nodemedia.cn/products/node-media-player/

http://live.nodemedia.cn/live/demo_144.flv 这样的地址。
因为demo地址有刷新 ，所以对应的不一定是144这个地址。

做法：
在demo地址里使用webrtc生成flv
然后在H5版本的flv播放器播放。


是我哪里使用不对吗？

**Comment by illuspas** [comment]
你用的什么浏览器

**Comment by zsinba** [comment]
Chrome ,应该是最新的版本。 有更新我都会更新的。
