### ISSUE TITLE
Is nms open source?

### ISSUE THREAD

**Issue by tian2992** [NodeMedia/NodeMediaServer#9]
Trying to understand the source of your repos and the website, i see nms mentioned, however there is no resource available for downloading the Go language source. 

Is NodeMediaServer an open source product?

**Comment by ben221199** [comment]
See #2

**Comment by tian2992** [comment]
Thanks, I do not understand chinese, but using translation it appears it is not open, therefore I guess i will be unable to use it.

Thank you.

**Comment by ben221199** [comment]
@illuspas Will NMSv3 ever be open source? Now we cannot add features to it and contribute to make the project even better.
